### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by cyberpewpew** [Mili-NT/Keyring#4]
```
  File "Keyring.py", line 54
    shodan_output = f'{curdir}/Output/ShodanKeys.txt'
                                                    ^
SyntaxError: invalid syntax
```
Encountered this error. Requirements have been installed.

**Comment by Mili-NT** [comment]
What OS and python version was this run in? I havent been able to reproduce that error in my linux or windows environment.
